/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package apresentacao;


import java.util.ArrayList;
import java.util.List;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import modelo.*;
/**
 *
 * @author User
 */
public class frmFinal extends javax.swing.JDialog
{

    /**
     * Creates new form frmFinal
     */
    public frmFinal(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        
        String porcentagens = Visitantes.pesquisaSatisfacao();
        txAAvalicaoSistema.setText(porcentagens); 
        
        String porcentagensacertos = Visitantes.porcentagensDeAcertos();
        txAPorcentagemAcerto.setText(porcentagensacertos);         


        lblNome.setText(Estaticos.NOME);
        lblTotalRespo.setText("Total de respondentes: " + Estaticos.SOMA);
        if(Estaticos.SOMAACERTOS >= 3){
            lblSituacao.setText("Parabens!!");
            lblAcertos.setText("Seu total de acerto foi: " + Estaticos.SOMAACERTOS);

        }else
        {
            lblSituacao.setText("Que pena!");
            lblAcertos.setText("Seu total de acerto foi: " + Estaticos.SOMAACERTOS);
        }
        
        
        
//        new java.util.Timer().schedule(new TimerTask() {
//            @Override
//            public void run() {
//                //executar ação aqui
//            btnFinalizar.doClick();
//            }
//        }, 30000);

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAcertos2 = new javax.swing.JLabel();
        lblTotalRespo = new javax.swing.JLabel();
        lblAcertos1 = new javax.swing.JLabel();
        spPorcentagemAcerto = new javax.swing.JScrollPane();
        txAPorcentagemAcerto = new javax.swing.JTextArea();
        spAvaliacaoSistema = new javax.swing.JScrollPane();
        txAAvalicaoSistema = new javax.swing.JTextArea();
        btnAvaliacaoSistema = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        btnporcetagem = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        lblAcertos = new javax.swing.JLabel();
        lblSituacao = new javax.swing.JLabel();
        btnMostrarDados = new javax.swing.JButton();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(1525, 790));
        setPreferredSize(new java.awt.Dimension(1525, 790));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAcertos2.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        lblAcertos2.setForeground(new java.awt.Color(164, 127, 85));
        lblAcertos2.setText("Porcentagem de acertos:");
        getContentPane().add(lblAcertos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 60, 250, 50));

        lblTotalRespo.setBackground(new java.awt.Color(74, 43, 23));
        lblTotalRespo.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        lblTotalRespo.setForeground(new java.awt.Color(164, 127, 85));
        lblTotalRespo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalRespo.setText("total de respondentes :");
        lblTotalRespo.setOpaque(true);
        getContentPane().add(lblTotalRespo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 700, 330, 40));

        lblAcertos1.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        lblAcertos1.setForeground(new java.awt.Color(164, 127, 85));
        lblAcertos1.setText("Avaliação do sistema:");
        getContentPane().add(lblAcertos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 210, 50));

        txAPorcentagemAcerto.setEditable(false);
        txAPorcentagemAcerto.setBackground(new java.awt.Color(128, 88, 53));
        txAPorcentagemAcerto.setColumns(20);
        txAPorcentagemAcerto.setFont(new java.awt.Font("Eras Bold ITC", 0, 28)); // NOI18N
        txAPorcentagemAcerto.setForeground(new java.awt.Color(74, 43, 23));
        txAPorcentagemAcerto.setLineWrap(true);
        txAPorcentagemAcerto.setRows(5);
        txAPorcentagemAcerto.setCaretColor(new java.awt.Color(0, 0, 0));
        txAPorcentagemAcerto.setFocusable(false);
        txAPorcentagemAcerto.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        spPorcentagemAcerto.setViewportView(txAPorcentagemAcerto);

        getContentPane().add(spPorcentagemAcerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 110, 280, 210));

        txAAvalicaoSistema.setEditable(false);
        txAAvalicaoSistema.setBackground(new java.awt.Color(128, 88, 53));
        txAAvalicaoSistema.setColumns(20);
        txAAvalicaoSistema.setFont(new java.awt.Font("Eras Bold ITC", 0, 28)); // NOI18N
        txAAvalicaoSistema.setForeground(new java.awt.Color(74, 43, 23));
        txAAvalicaoSistema.setLineWrap(true);
        txAAvalicaoSistema.setRows(5);
        txAAvalicaoSistema.setBorder(null);
        txAAvalicaoSistema.setCaretColor(new java.awt.Color(0, 0, 0));
        txAAvalicaoSistema.setFocusable(false);
        txAAvalicaoSistema.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        spAvaliacaoSistema.setViewportView(txAAvalicaoSistema);

        getContentPane().add(spAvaliacaoSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 250, 170));

        btnAvaliacaoSistema.setBackground(new java.awt.Color(74, 43, 23));
        btnAvaliacaoSistema.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        btnAvaliacaoSistema.setForeground(new java.awt.Color(164, 127, 85));
        btnAvaliacaoSistema.setText("Avaliação do sistema");
        btnAvaliacaoSistema.setBorder(null);
        btnAvaliacaoSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvaliacaoSistemaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAvaliacaoSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 670, 240, 40));

        btnFinalizar.setBackground(new java.awt.Color(74, 43, 23));
        btnFinalizar.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        btnFinalizar.setForeground(new java.awt.Color(164, 127, 85));
        btnFinalizar.setText("Finalizar");
        btnFinalizar.setBorder(null);
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 640, 150, 60));

        btnporcetagem.setBackground(new java.awt.Color(74, 43, 23));
        btnporcetagem.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        btnporcetagem.setForeground(new java.awt.Color(164, 127, 85));
        btnporcetagem.setText("Porcentagem de Acertos");
        btnporcetagem.setAlignmentX(600.0F);
        btnporcetagem.setBorder(null);
        btnporcetagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnporcetagemActionPerformed(evt);
            }
        });
        getContentPane().add(btnporcetagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 240, 40));

        lblNome.setBackground(new java.awt.Color(74, 43, 23));
        lblNome.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        lblNome.setForeground(new java.awt.Color(164, 127, 85));
        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNome.setText("seu nome");
        lblNome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1520, 40));

        lblAcertos.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        lblAcertos.setForeground(new java.awt.Color(164, 127, 85));
        lblAcertos.setText("Total de acertos: ");
        getContentPane().add(lblAcertos, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 320, 50));

        lblSituacao.setBackground(new java.awt.Color(74, 43, 23));
        lblSituacao.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        lblSituacao.setForeground(new java.awt.Color(164, 127, 85));
        lblSituacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSituacao.setText("Parabéns!!");
        lblSituacao.setAlignmentY(0.0F);
        getContentPane().add(lblSituacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1525, 40));

        btnMostrarDados.setBackground(new java.awt.Color(74, 43, 23));
        btnMostrarDados.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        btnMostrarDados.setForeground(new java.awt.Color(164, 127, 85));
        btnMostrarDados.setText("Classificação");
        btnMostrarDados.setBorder(null);
        btnMostrarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarDadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrarDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, 240, 40));

        lblFundo.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FundoGeral.jpg"))); // NOI18N
        lblFundo.setAlignmentY(0.0F);
        getContentPane().add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnFinalizarActionPerformed
    {//GEN-HEADEREND:event_btnFinalizarActionPerformed
        frmInicial frmI = new frmInicial(null, true);
        this.setVisible(false);
        frmI.setVisible(true);
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnMostrarDadosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnMostrarDadosActionPerformed
    {//GEN-HEADEREND:event_btnMostrarDadosActionPerformed
    // Cria uma cópia da lista de visitantes
    List<Visitantes> visitantesOrdenados = new ArrayList<>(Visitantes.getListaVisitantes());

    // Ordena os visitantes pelo número de acertos em ordem decrescente
    visitantesOrdenados.sort((v1, v2) -> {
        int acertosV1 = Integer.parseInt(v1.acertos);
        int acertosV2 = Integer.parseInt(v2.acertos);
        return Integer.compare(acertosV2, acertosV1); // Decrescente
    });

    // Cria uma instância de StringBuilder para construir a string de saída
    StringBuilder sb = new StringBuilder();

    // Adiciona os visitantes ao StringBuilder, em ordem de ranking
    int rank = 1;
    for (Visitantes visitante : visitantesOrdenados) {
        sb.append("Rank ").append(rank).append(": ").append(visitante.toString()).append("\n");
        rank++;
    }

    // Exibe uma caixa de diálogo com o conteúdo do StringBuilder, que contém o ranking dos visitantes
    JOptionPane.showMessageDialog(null, sb.toString(), "Ranking de Visitantes", JOptionPane.INFORMATION_MESSAGE);
        

    }//GEN-LAST:event_btnMostrarDadosActionPerformed

    private void btnporcetagemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnporcetagemActionPerformed
    {//GEN-HEADEREND:event_btnporcetagemActionPerformed
       String porcentagens = Visitantes.porcentagensDeAcertos();

       // Exibir o resultado em uma caixa de diálogo
       JOptionPane.showMessageDialog(null, porcentagens, "Porcentagem de Acertos", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnporcetagemActionPerformed

    private void btnAvaliacaoSistemaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAvaliacaoSistemaActionPerformed
    {//GEN-HEADEREND:event_btnAvaliacaoSistemaActionPerformed
       String pesquisaSatisfacao = Visitantes.pesquisaSatisfacao();

       // Exibir o resultado em uma caixa de diálogo
       JOptionPane.showMessageDialog(null, pesquisaSatisfacao, "Porcentagem de Acertos", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAvaliacaoSistemaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                frmFinal dialog = new frmFinal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvaliacaoSistema;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnMostrarDados;
    private javax.swing.JButton btnporcetagem;
    private javax.swing.JLabel lblAcertos;
    private javax.swing.JLabel lblAcertos1;
    private javax.swing.JLabel lblAcertos2;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSituacao;
    private javax.swing.JLabel lblTotalRespo;
    private javax.swing.JScrollPane spAvaliacaoSistema;
    private javax.swing.JScrollPane spPorcentagemAcerto;
    private javax.swing.JTextArea txAAvalicaoSistema;
    private javax.swing.JTextArea txAPorcentagemAcerto;
    // End of variables declaration//GEN-END:variables
}
