/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package apresentacao;


import modelo.*;

/**
 *
 * @author User
 */
public class frmPergunta5 extends javax.swing.JDialog
{
    String resp5;
    String acertos;
    
    /**
     * Creates new form frmPergunta2
     */
    public frmPergunta5(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbtnP5 = new javax.swing.ButtonGroup();
        lblPergunta5 = new javax.swing.JLabel();
        rbdP5A = new javax.swing.JRadioButton();
        rbdP5B = new javax.swing.JRadioButton();
        rbdP5C = new javax.swing.JRadioButton();
        lblTotalRespo = new javax.swing.JLabel();
        lblResposta = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(1525, 790));
        setPreferredSize(new java.awt.Dimension(1525, 790));
        setResizable(false);
        getContentPane().setLayout(null);

        lblPergunta5.setBackground(new java.awt.Color(74, 43, 23));
        lblPergunta5.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        lblPergunta5.setForeground(new java.awt.Color(164, 127, 85));
        lblPergunta5.setText("Pergunta 5: Em 2020 quantas sondas foram lançadas a marte? ");
        getContentPane().add(lblPergunta5);
        lblPergunta5.setBounds(420, 140, 590, 22);

        rbdP5A.setBackground(new java.awt.Color(164, 127, 85));
        gbtnP5.add(rbdP5A);
        rbdP5A.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        rbdP5A.setForeground(new java.awt.Color(74, 43, 23));
        rbdP5A.setText("a) 4");
        rbdP5A.setBorder(null);
        getContentPane().add(rbdP5A);
        rbdP5A.setBounds(420, 190, 110, 24);

        rbdP5B.setBackground(new java.awt.Color(164, 127, 85));
        gbtnP5.add(rbdP5B);
        rbdP5B.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        rbdP5B.setForeground(new java.awt.Color(74, 43, 23));
        rbdP5B.setText("b) 1");
        rbdP5B.setBorder(null);
        getContentPane().add(rbdP5B);
        rbdP5B.setBounds(420, 250, 110, 24);

        rbdP5C.setBackground(new java.awt.Color(164, 127, 85));
        gbtnP5.add(rbdP5C);
        rbdP5C.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        rbdP5C.setForeground(new java.awt.Color(74, 43, 23));
        rbdP5C.setText("c) 3");
        rbdP5C.setBorder(null);
        getContentPane().add(rbdP5C);
        rbdP5C.setBounds(420, 310, 110, 24);

        lblTotalRespo.setBackground(new java.awt.Color(74, 43, 23));
        lblTotalRespo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTotalRespo.setForeground(new java.awt.Color(164, 127, 85));
        getContentPane().add(lblTotalRespo);
        lblTotalRespo.setBounds(189, 692, 203, 0);

        lblResposta.setBackground(new java.awt.Color(74, 43, 23));
        lblResposta.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblResposta.setForeground(new java.awt.Color(164, 127, 85));
        getContentPane().add(lblResposta);
        lblResposta.setBounds(35, 588, 107, 0);

        btnContinuar.setBackground(new java.awt.Color(74, 43, 23));
        btnContinuar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(164, 127, 85));
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(btnContinuar);
        btnContinuar.setBounds(1240, 670, 150, 60);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FundoGeral.jpg"))); // NOI18N
        lblFundo.setAlignmentY(0.0F);
        getContentPane().add(lblFundo);
        lblFundo.setBounds(0, 0, 1525, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnContinuarActionPerformed
    {//GEN-HEADEREND:event_btnContinuarActionPerformed
        if (rbdP5C.isSelected())
        {
           Estaticos.RESP5 = "acerto";
            Estaticos.SOMAACERTOS++; 
            frmPesquisaSatisfacao frmPS = new frmPesquisaSatisfacao(null, true);
            this.setVisible(false);
            frmPS.setVisible(true);             

        }
        else
        {
            Estaticos.RESP5 = "erro";
            frmPesquisaSatisfacao frmPS = new frmPesquisaSatisfacao(null, true);
            this.setVisible(false);
            frmPS.setVisible(true);       
        } 
        
        
        
//        if (rbdP5C.isSelected())
//        {
//            resp5 = "acerto";
//            Estaticos.SOMAACERTOS++; 
//        }
//        else
//        {
//            resp5 = "erro";
//        }
//        
//        Estaticos.SOMA++;
//        
//        int somaAcertos = Estaticos.SOMAACERTOS;
//        acertos = Integer.toString(somaAcertos);
//        
//        
//        Controle controle = new Controle(Estaticos.NOME, Estaticos.RESP1, Estaticos.RESP2, Estaticos.RESP3, Estaticos.RESP4, resp5, acertos);
//
//        
//
//        
//        frmPesquisaSatisfacao frmPS = new frmPesquisaSatisfacao(null, true);
//        this.setVisible(false);
//        frmPS.setVisible(true);
    }//GEN-LAST:event_btnContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmPergunta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmPergunta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmPergunta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmPergunta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                frmPergunta2 dialog = new frmPergunta2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.ButtonGroup gbtnP5;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblPergunta5;
    private javax.swing.JLabel lblResposta;
    private javax.swing.JLabel lblTotalRespo;
    private javax.swing.JRadioButton rbdP5A;
    private javax.swing.JRadioButton rbdP5B;
    private javax.swing.JRadioButton rbdP5C;
    // End of variables declaration//GEN-END:variables
}
