/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package apresentacao;


import modelo.*;

/**
 *
 * @author User
 */
public class frmPergunta2 extends javax.swing.JDialog
{

    
    /**
     * Creates new form frmPergunta2
     */
    public frmPergunta2(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbtnP2 = new javax.swing.ButtonGroup();
        lblPergunta2 = new javax.swing.JLabel();
        rbdP2A = new javax.swing.JRadioButton();
        rbdP2B = new javax.swing.JRadioButton();
        rbdP2C = new javax.swing.JRadioButton();
        lblTotalRespo = new javax.swing.JLabel();
        lblResposta = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(1525, 790));
        setPreferredSize(new java.awt.Dimension(1525, 790));
        setResizable(false);
        getContentPane().setLayout(null);

        lblPergunta2.setBackground(new java.awt.Color(74, 43, 23));
        lblPergunta2.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        lblPergunta2.setForeground(new java.awt.Color(164, 127, 85));
        lblPergunta2.setText("Pergunta 2: Qual foi o primeiro rover a pousar em Marte? ");
        getContentPane().add(lblPergunta2);
        lblPergunta2.setBounds(420, 140, 550, 22);

        rbdP2A.setBackground(new java.awt.Color(74, 43, 23));
        gbtnP2.add(rbdP2A);
        rbdP2A.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        rbdP2A.setForeground(new java.awt.Color(164, 127, 85));
        rbdP2A.setText("a) Spirit");
        rbdP2A.setBorder(null);
        getContentPane().add(rbdP2A);
        rbdP2A.setBounds(420, 210, 110, 24);

        rbdP2B.setBackground(new java.awt.Color(74, 43, 23));
        gbtnP2.add(rbdP2B);
        rbdP2B.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        rbdP2B.setForeground(new java.awt.Color(164, 127, 85));
        rbdP2B.setText("b) Perseverance");
        rbdP2B.setBorder(null);
        getContentPane().add(rbdP2B);
        rbdP2B.setBounds(420, 260, 180, 24);

        rbdP2C.setBackground(new java.awt.Color(74, 43, 23));
        gbtnP2.add(rbdP2C);
        rbdP2C.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        rbdP2C.setForeground(new java.awt.Color(164, 127, 85));
        rbdP2C.setText("c) Sojurner");
        rbdP2C.setBorder(null);
        getContentPane().add(rbdP2C);
        rbdP2C.setBounds(420, 310, 140, 24);

        lblTotalRespo.setBackground(new java.awt.Color(74, 43, 23));
        lblTotalRespo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTotalRespo.setForeground(new java.awt.Color(164, 127, 85));
        getContentPane().add(lblTotalRespo);
        lblTotalRespo.setBounds(189, 692, 203, 0);

        lblResposta.setBackground(new java.awt.Color(74, 43, 23));
        lblResposta.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblResposta.setForeground(new java.awt.Color(164, 127, 85));
        getContentPane().add(lblResposta);
        lblResposta.setBounds(35, 588, 107, 0);

        btnContinuar.setBackground(new java.awt.Color(74, 43, 23));
        btnContinuar.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(164, 127, 85));
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(btnContinuar);
        btnContinuar.setBounds(1240, 670, 150, 60);

        lblFundo.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FundoGeral.jpg"))); // NOI18N
        lblFundo.setAlignmentY(0.0F);
        getContentPane().add(lblFundo);
        lblFundo.setBounds(0, 0, 1525, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnContinuarActionPerformed
    {//GEN-HEADEREND:event_btnContinuarActionPerformed
         if (rbdP2C.isSelected())
        {
            Estaticos.RESP2 = "acerto";
            Estaticos.SOMAACERTOS++; 
            frmPergunta3 frmP3 = new frmPergunta3(null, true);
            this.setVisible(false);
            frmP3.setVisible(true);           

        }
        else
        {
            Estaticos.RESP2 = "erro";
            frmPergunta3 frmP3 = new frmPergunta3(null, true);
            this.setVisible(false);
            frmP3.setVisible(true);     
        } 
         
         
      
//        
//        if (rbdP3A.isSelected())
//        {
//            resp3 = "acerto";
//            Estaticos.SOMAACERTOS++; 
//        }
//        else
//        {
//            resp3 = "erro";
//        } 
//        
//        
//        if (rbdP4C.isSelected())
//        {
//            resp4 = "acerto";
//            Estaticos.SOMAACERTOS++; 
//        }
//        else
//        {
//            resp4 = "erro";
//        } 
//        
//        
//        if (rbdP5C.isSelected())
//        {
//            resp5 = "acerto";
//            Estaticos.SOMAACERTOS++; 
//        }
//        else
//        {
//            resp5 = "erro";
//        }    
//        
//        Controle controle = new Controle(Estaticos.NOME, Estaticos.RESP1, resp2, resp3, resp4, resp5);
//
//        Estaticos.SOMA++;
//
//        
//        frmFinal frmF = new frmFinal(null, true);
//        this.setVisible(false);
//        frmF.setVisible(true);
    }//GEN-LAST:event_btnContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmPergunta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmPergunta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmPergunta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmPergunta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                frmPergunta2 dialog = new frmPergunta2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.ButtonGroup gbtnP2;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblPergunta2;
    private javax.swing.JLabel lblResposta;
    private javax.swing.JLabel lblTotalRespo;
    private javax.swing.JRadioButton rbdP2A;
    private javax.swing.JRadioButton rbdP2B;
    private javax.swing.JRadioButton rbdP2C;
    // End of variables declaration//GEN-END:variables
}
