/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package apresentacao;


import modelo.*;

/**
 *
 * @author User
 */
public class frmPergunta3 extends javax.swing.JDialog
{

    
    /**
     * Creates new form frmPergunta2
     */
    public frmPergunta3(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbtnP3 = new javax.swing.ButtonGroup();
        lblPergunta3 = new javax.swing.JLabel();
        rbdP3B = new javax.swing.JRadioButton();
        rbdP3C = new javax.swing.JRadioButton();
        rbdP3A = new javax.swing.JRadioButton();
        lblTotalRespo = new javax.swing.JLabel();
        lblResposta = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(1525, 790));
        setPreferredSize(new java.awt.Dimension(1525, 790));
        setResizable(false);
        getContentPane().setLayout(null);

        lblPergunta3.setBackground(new java.awt.Color(74, 43, 23));
        lblPergunta3.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        lblPergunta3.setForeground(new java.awt.Color(164, 127, 85));
        lblPergunta3.setText("Pergunta 3: Qual dessas sondas teve o primeiro drone de apoio a voar em Marte? ");
        getContentPane().add(lblPergunta3);
        lblPergunta3.setBounds(420, 140, 770, 22);

        rbdP3B.setBackground(new java.awt.Color(74, 43, 23));
        gbtnP3.add(rbdP3B);
        rbdP3B.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        rbdP3B.setForeground(new java.awt.Color(164, 127, 85));
        rbdP3B.setText("b) Curiosity");
        rbdP3B.setBorder(null);
        getContentPane().add(rbdP3B);
        rbdP3B.setBounds(420, 270, 150, 24);

        rbdP3C.setBackground(new java.awt.Color(74, 43, 23));
        gbtnP3.add(rbdP3C);
        rbdP3C.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        rbdP3C.setForeground(new java.awt.Color(164, 127, 85));
        rbdP3C.setText("c) Opportunity");
        rbdP3C.setBorder(null);
        rbdP3C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbdP3CActionPerformed(evt);
            }
        });
        getContentPane().add(rbdP3C);
        rbdP3C.setBounds(420, 330, 170, 24);

        rbdP3A.setBackground(new java.awt.Color(74, 43, 23));
        gbtnP3.add(rbdP3A);
        rbdP3A.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        rbdP3A.setForeground(new java.awt.Color(164, 127, 85));
        rbdP3A.setText("a) Perseverance");
        rbdP3A.setBorder(null);
        getContentPane().add(rbdP3A);
        rbdP3A.setBounds(420, 210, 180, 24);

        lblTotalRespo.setBackground(new java.awt.Color(74, 43, 23));
        lblTotalRespo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTotalRespo.setForeground(new java.awt.Color(164, 127, 85));
        getContentPane().add(lblTotalRespo);
        lblTotalRespo.setBounds(189, 692, 203, 0);

        lblResposta.setBackground(new java.awt.Color(74, 43, 23));
        lblResposta.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblResposta.setForeground(new java.awt.Color(164, 127, 85));
        getContentPane().add(lblResposta);
        lblResposta.setBounds(35, 588, 107, 0);

        btnContinuar.setBackground(new java.awt.Color(74, 43, 23));
        btnContinuar.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(164, 127, 85));
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(btnContinuar);
        btnContinuar.setBounds(1240, 670, 150, 60);

        lblFundo.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FundoGeral.jpg"))); // NOI18N
        lblFundo.setAlignmentY(0.0F);
        getContentPane().add(lblFundo);
        lblFundo.setBounds(10, 0, 1525, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnContinuarActionPerformed
    {//GEN-HEADEREND:event_btnContinuarActionPerformed
  
        if (rbdP3A.isSelected())
        {
            Estaticos.RESP3 = "acerto";
            Estaticos.SOMAACERTOS++; 
            frmPergunta4 frmP4 = new frmPergunta4(null, true);
            this.setVisible(false);
            frmP4.setVisible(true);           

        }
        else
        {
            Estaticos.RESP3 = "erro";
            frmPergunta4 frmP4 = new frmPergunta4(null, true);
            this.setVisible(false);
            frmP4.setVisible(true);   
        } 

        
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void rbdP3CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbdP3CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbdP3CActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmPergunta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmPergunta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmPergunta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmPergunta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                frmPergunta3 dialog = new frmPergunta3(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.ButtonGroup gbtnP3;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblPergunta3;
    private javax.swing.JLabel lblResposta;
    private javax.swing.JLabel lblTotalRespo;
    private javax.swing.JRadioButton rbdP3A;
    private javax.swing.JRadioButton rbdP3B;
    private javax.swing.JRadioButton rbdP3C;
    // End of variables declaration//GEN-END:variables
}
