/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package apresentacao;


import modelo.*;

/**
 *
 * @author User
 */
public class frmPergunta4 extends javax.swing.JDialog
{
    
    /**
     * Creates new form frmPergunta2
     */
    public frmPergunta4(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbtnP4 = new javax.swing.ButtonGroup();
        lblPergunta4 = new javax.swing.JLabel();
        rbdP4A = new javax.swing.JRadioButton();
        rbdP4B = new javax.swing.JRadioButton();
        rbdP4C = new javax.swing.JRadioButton();
        lblTotalRespo = new javax.swing.JLabel();
        lblResposta = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(1525, 790));
        setPreferredSize(new java.awt.Dimension(1525, 790));
        setResizable(false);
        getContentPane().setLayout(null);

        lblPergunta4.setBackground(new java.awt.Color(74, 43, 23));
        lblPergunta4.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        lblPergunta4.setForeground(new java.awt.Color(164, 127, 85));
        lblPergunta4.setText("Pergunta 4: Qual foi a região designada para o pouso da sonda Curiosity em 2012? ");
        getContentPane().add(lblPergunta4);
        lblPergunta4.setBounds(420, 140, 780, 22);

        rbdP4A.setBackground(new java.awt.Color(164, 127, 85));
        gbtnP4.add(rbdP4A);
        rbdP4A.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        rbdP4A.setForeground(new java.awt.Color(74, 43, 23));
        rbdP4A.setText("a) Cratera de Jazero");
        rbdP4A.setBorder(null);
        getContentPane().add(rbdP4A);
        rbdP4A.setBounds(420, 210, 220, 24);

        rbdP4B.setBackground(new java.awt.Color(164, 127, 85));
        gbtnP4.add(rbdP4B);
        rbdP4B.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        rbdP4B.setForeground(new java.awt.Color(74, 43, 23));
        rbdP4B.setText("b) Ares Vallis");
        rbdP4B.setBorder(null);
        getContentPane().add(rbdP4B);
        rbdP4B.setBounds(420, 280, 160, 24);

        rbdP4C.setBackground(new java.awt.Color(164, 127, 85));
        gbtnP4.add(rbdP4C);
        rbdP4C.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        rbdP4C.setForeground(new java.awt.Color(74, 43, 23));
        rbdP4C.setText("c) Cratera Gale");
        rbdP4C.setBorder(null);
        rbdP4C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbdP4CActionPerformed(evt);
            }
        });
        getContentPane().add(rbdP4C);
        rbdP4C.setBounds(420, 340, 170, 24);

        lblTotalRespo.setBackground(new java.awt.Color(74, 43, 23));
        lblTotalRespo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTotalRespo.setForeground(new java.awt.Color(164, 127, 85));
        getContentPane().add(lblTotalRespo);
        lblTotalRespo.setBounds(189, 692, 203, 0);

        lblResposta.setBackground(new java.awt.Color(74, 43, 23));
        lblResposta.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblResposta.setForeground(new java.awt.Color(164, 127, 85));
        getContentPane().add(lblResposta);
        lblResposta.setBounds(35, 588, 107, 0);

        btnContinuar.setBackground(new java.awt.Color(74, 43, 23));
        btnContinuar.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(164, 127, 85));
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(btnContinuar);
        btnContinuar.setBounds(1240, 670, 150, 60);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FundoGeral.jpg"))); // NOI18N
        lblFundo.setAlignmentY(0.0F);
        getContentPane().add(lblFundo);
        lblFundo.setBounds(0, 0, 1525, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnContinuarActionPerformed
    {//GEN-HEADEREND:event_btnContinuarActionPerformed

        
        
        if (rbdP4C.isSelected())
        {
           Estaticos.RESP4 = "acerto";
            Estaticos.SOMAACERTOS++; 
            frmPergunta5 frmP5 = new frmPergunta5(null, true);
            this.setVisible(false);
            frmP5.setVisible(true);           

        }
        else
        {
            Estaticos.RESP4 = "erro";
            frmPergunta5 frmP5 = new frmPergunta5(null, true);
            this.setVisible(false);
            frmP5.setVisible(true);       
        } 
        
  
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void rbdP4CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbdP4CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbdP4CActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmPergunta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmPergunta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmPergunta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmPergunta2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                frmPergunta2 dialog = new frmPergunta2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.ButtonGroup gbtnP4;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblPergunta4;
    private javax.swing.JLabel lblResposta;
    private javax.swing.JLabel lblTotalRespo;
    private javax.swing.JRadioButton rbdP4A;
    private javax.swing.JRadioButton rbdP4B;
    private javax.swing.JRadioButton rbdP4C;
    // End of variables declaration//GEN-END:variables
}
